# Generated by Django 4.2.4 on 2023-08-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashnot',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('Programmer', 'Programmer'), ('Developer', 'Developer')], max_length=100)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
