# Generated by Django 4.2.4 on 2023-08-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hashnotuser_remove_hashnot_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashnot',
            name='username',
            field=models.CharField(default=models.AutoField(primary_key=True, serialize=False), max_length=15),
        ),
    ]
