# Generated by Django 4.2.4 on 2023-08-30 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hashnot_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashnotuser',
            name='contest_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='hashnotuser',
            name='op_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hashnot'),
        ),
        migrations.AddField(
            model_name='hashnotuser',
            name='required_skills',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hashnotuser',
            name='post_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hashnotuser',
            name='post_subject',
            field=models.TextField(null=True),
        ),
    ]
