# Generated by Django 4.2.4 on 2023-08-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hashnotuser_contest_link_hashnotuser_op_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashnot',
            name='community_respect',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='hashnot',
            name='username',
            field=models.CharField(default=models.AutoField(primary_key=True, serialize=False), max_length=40),
        ),
    ]
