# Generated by Django 4.2.4 on 2023-08-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_hashnot_community_respect_alter_hashnot_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashnot',
            name='github_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='hashnot',
            name='other_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='hashnotuser',
            name='post_reports',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hashnotuser',
            name='post_score',
            field=models.IntegerField(default=10),
        ),
    ]
